"""Definições e catálogo de domínio dos fertilizantes homologados no FertiPartner.

Catálogo técnico e agronômico detalhado com especificações químicas, físicas,
culturas alvo, dinâmicas no solo, armazenagem e classificações alfandegárias (NCM/HS).
"""

from typing import Any

FERTILIZERS_CATALOG: list[dict[str, Any]] = [
    {
        "id": 1,
        "slug": "ureia",
        "canonical_name": "Ureia",
        "category_name": "Fertilizantes Nitrogenados",
        "chemical_formula": "CO(NH2)2",
        "cas_rn": "57-13-6",
        "description": "Fertilizante nitrogenado sólido de mais alta concentração (46% N), amplamente utilizado no mundo e no Brasil.",
        "detailed_description": "A ureia é sintetizada a partir da reação de amônia anidra líquida com dióxido de carbono sob alta pressão (150-200 bar) e temperatura (180-200 °C), formando carbamato de amônio intermediário desidratado em grânulos ou pérolas de alta pureza.",
        "agronomic_usage": "Principal fonte de Nitrogênio (N) em cobertura para milho, cana-de-açúcar, algodão e pastagens. Sujeita a perdas por volatilização de amônia (NH3) em superfície sob calor e umidade, sendo recomendada incorporação mecânica no solo ou uso de inibidores de urease (NBPT).",
        "physical_properties": "Grânulos brancos esféricos, altamente solúveis em água (1.080 g/L a 20 °C). Solução aquosa de reação neutra a levemente alcalina. Densidade aparente aproximada de 0,74 a 0,78 g/cm³.",
        "handling_storage": "Alta higroscopicidade com Ponto Crítico de Umidade Relativa (PCUR) de 75% a 30 °C. Exige armazenamento em ambiente coberto, seco e sobre estrados. Incompatível para mistura física a granel com nitrato de amônio e superfosfatos com acidez livre.",
        "typical_nutrients": {"N (Nitrogênio Total)": 46.0},
        "synonyms": ["Carbamide", "Urea", "Ureia 46%", "Carbamida"],
        "hs_ncm_codes": ["310210", "31021010"],
    },
    {
        "id": 2,
        "slug": "map",
        "canonical_name": "Fosfato Monoamônico (MAP)",
        "category_name": "Fertilizantes Fosfatados",
        "chemical_formula": "NH4H2PO4",
        "cas_rn": "7722-76-1",
        "description": "Fertilizante fosfatado concentrado fornecendo Nitrogênio (11%) e Fósforo (52% P2O5).",
        "detailed_description": "Obtido pela reação entre ácido fosfórico de via úmida purificado e amônia anidra gasosa em reatores tubulares (pipe-reactors), gerando grânulos duros e uniformes com alto teor de P2O5 solúvel em água e citrato neutro de amônio.",
        "agronomic_usage": "Carro-chefe da adubação de plantio (sulco de semeadura) para soja, milho e algodão no Cerrado brasileiro. O fósforo estimula o enraizamento inicial vigoroso e o nitrogênio amoniacal (NH4+) estimula o sinergismo na absorção do fosfato pelas raízes.",
        "physical_properties": "Grânulos esféricos marrons a cinzas, alta solubilidade aquosa (370 g/L a 20 °C). Reação residual ácida em solução (pH 4,0 a 4,5), benéfica em solos alcalinos ou calcários. Densidade aparente: 0,95 a 1,00 g/cm³.",
        "handling_storage": "Excelente estabilidade física e baixa higroscopicidade (PCUR de 92% a 30 °C). Alta compatibilidade em misturas físicas com KCl e sulfato de amônio. Manter em local ventilado e seco.",
        "typical_nutrients": {"N (Nitrogênio)": 11.0, "P2O5 (Pentóxido de Fósforo Solúvel)": 52.0},
        "synonyms": ["MAP", "Monoammonium Phosphate", "Fosfato Monoamônico Granulado"],
        "hs_ncm_codes": ["310540", "31054000"],
    },
    {
        "id": 3,
        "slug": "dap",
        "canonical_name": "Fosfato Diamônico (DAP)",
        "category_name": "Fertilizantes Fosfatados",
        "chemical_formula": "(NH4)2HPO4",
        "cas_rn": "7783-28-0",
        "description": "Fertilizante fosfatado de alta solubilidade contendo 18% N e 46% P2O5.",
        "detailed_description": "Produzido pela reação contínua em duas etapas de amônia anidra com ácido fosfórico, promovendo relação molar N:P de aproximadamente 2:1, seguido por granulação e secagem em tambores rotativos.",
        "agronomic_usage": "Muito utilizado no plantio de grãos internacionalmente e no sul do Brasil. Em solos muito ácidos com alta CTC, sua dissolução gera uma microrregião alcalina temporária que pode liberar amônia livre transitória próxima às sementes, requerendo cuidado na proximidade do sulco.",
        "physical_properties": "Grânulos cinzas ou escuros, muito solúveis em água (575 g/L a 20 °C). Reação em solução levemente básica (pH 7,5 a 8,0). Densidade aparente: 0,90 a 0,95 g/cm³.",
        "handling_storage": "Boa estabilidade de armazenamento (PCUR de 82% a 30 °C). Não deve ser misturado com fertilizantes com cal viva ou escórias sob risco de liberação gasosa de amônia.",
        "typical_nutrients": {"N (Nitrogênio)": 18.0, "P2O5 (Pentóxido de Fósforo Solúvel)": 46.0},
        "synonyms": ["DAP", "Diammonium Phosphate", "Fosfato Diamônico"],
        "hs_ncm_codes": ["310530", "31053000"],
    },
    {
        "id": 4,
        "slug": "cloreto-de-potassio",
        "canonical_name": "Cloreto de Potássio (KCl / MOP)",
        "category_name": "Fertilizantes Potássicos",
        "chemical_formula": "KCl",
        "cas_rn": "7447-40-7",
        "description": "Fonte potássica predominante mundialmente, garantindo 60% de K2O solúvel em água.",
        "detailed_description": "Extraído por mineração subterrânea de rochas evaporíticas (silvinita e carnalita) ou evaporação solar de salmouras, seguido por flotação por espumas, recristalização térmica e compactação mecânica em grânulos avermelhados (pela presença de traços de óxido de ferro) ou brancos.",
        "agronomic_usage": "Essencial para os processos de osmorregulação, abertura estomática, síntese de amido e transporte de fotoassimilados em soja, milho, cana e café. O Brasil importa mais de 95% de sua demanda nacional. Possui alto índice de salinidade (116), exigindo fracionamento de doses pesadas.",
        "physical_properties": "Grânulos cristalinos vermelhos/rosa ou brancos, totalmente solúveis em água (340 g/L a 20 °C). Reação neutra em solução aquosa (pH 7,0). Densidade aparente de 1,00 a 1,05 g/cm³.",
        "handling_storage": "Moderadamente higroscópico (PCUR de 84% a 30 °C). Sujeito a empedramento físico em condições de alta umidade relativa (>85%) se armazenado por longos períodos em pilhas altas.",
        "typical_nutrients": {"K2O (Óxido de Potássio Solúvel)": 60.0},
        "synonyms": ["KCl", "MOP", "Muriate of Potash", "Silvita Refinada"],
        "hs_ncm_codes": ["310420", "31042090"],
    },
    {
        "id": 5,
        "slug": "amonia-anidra",
        "canonical_name": "Amônia Anidra",
        "category_name": "Fertilizantes Nitrogenados",
        "chemical_formula": "NH3",
        "cas_rn": "7664-41-7",
        "description": "Matéria-prima básica fundamental para quase todos os fertilizantes nitrogenados (82% N).",
        "detailed_description": "Gás sintetizado pelo processo catalítico de Haber-Bosch a partir do nitrogênio atmosférico (N2) e hidrogênio (H2) obtido por reforma a vapor do gás natural. Mantida e transportada sob forma líquida pressurizada ou refrigerada a -33 °C.",
        "agronomic_usage": "Aplicação direta no solo por injeção pressurizada subsuperficial profunda (15 a 20 cm) em países como os EUA. No Brasil, seu uso é predominantemente industrial como insumo para fabricação de ureia, nitrato de amônio, MAP e DAP.",
        "physical_properties": "Gás incolor de odor pungente sufocante à pressão atmosférica, líquido límpido sob pressão (>8 bar a 20 °C). Extremamente solúvel em água formando hidróxido de amônio com liberação vigorosa de calor.",
        "handling_storage": "Produto perigoso de Classe 2 (gás comprimido e tóxico). Armazenamento em tanques criogênicos isolados ou esferas pressurizadas de aço carbono, exigindo sistemas de alívio e válvulas de segurança de emergência.",
        "typical_nutrients": {"N (Nitrogênio)": 82.0},
        "synonyms": ["Anhydrous Ammonia", "Amônia Líquida Industrial"],
        "hs_ncm_codes": ["281410", "28141000"],
    },
    {
        "id": 6,
        "slug": "nitrato-de-amonio",
        "canonical_name": "Nitrato de Amônio",
        "category_name": "Fertilizantes Nitrogenados",
        "chemical_formula": "NH4NO3",
        "cas_rn": "6484-52-2",
        "description": "Fertilizante nitrogenado com ação rápida e residual (33% a 34% N).",
        "detailed_description": "Produzido pela neutralização exotérmica de ácido nítrico (HNO3) com amônia gasosa (NH3), concentrado sob vácuo e granulado em torres de perolização ou granuladores de leito fluidizado com aditivos antiumectantes.",
        "agronomic_usage": "Excelente para adubação de cobertura em culturas perenes (café, citros e cana). Fornece nitrogênio prontamente disponível na forma nítrica (NO3-) de absorção imediata e amoniacal (NH4+) de ação mais duradoura, sem perdas significativas por volatilização em solos ácidos.",
        "physical_properties": "Grânulos ou pérolas brancas uniformes, altíssima solubilidade em água (1.920 g/L a 20 °C). Dissolução fortemente endotérmica (resfria a solução). Densidade: 0,86 a 0,92 g/cm³.",
        "handling_storage": "Altamente higroscópico (PCUR de 59% a 30 °C). Exige controle rigoroso de segurança pelo Exército Brasileiro por ser um agente oxidante forte. Proibido misturar com materiais orgânicos, combustíveis ou fontes de cloro.",
        "typical_nutrients": {"N (Nitrogênio Nítrico + Amoniacal)": 34.0},
        "synonyms": ["Ammonium Nitrate", "Nitrato de Amônio Perolado"],
        "hs_ncm_codes": ["310230", "31023000"],
    },
    {
        "id": 7,
        "slug": "sulfato-de-amonio",
        "canonical_name": "Sulfato de Amônio",
        "category_name": "Fertilizantes Nitrogenados",
        "chemical_formula": "(NH4)2SO4",
        "cas_rn": "7783-20-2",
        "description": "Fonte sólida combinada de Nitrogênio (21% N) e Enxofre (24% S).",
        "detailed_description": "Obtido principalmente como coproduto industrial na fabricação de caprolactama (nylon), refino petroquímico e dessulfurização de gases de coqueria, ou sintetizado diretamente pela reação de ácido sulfúrico com amônia.",
        "agronomic_usage": "Fundamental para culturas com alta demanda de enxofre como soja, milho, feijão e algodão. O enxofre na forma de sulfato (SO4²-) é prontamente assimilável pelas raízes, participando ativamente na síntese dos aminoácidos cisteína e metionina.",
        "physical_properties": "Cristais ou grânulos compactados brancos ou levemente amarelados/acinzentados. Boa solubilidade em água (750 g/L a 20 °C). Gera acidez residual moderada no solo ao longo dos anos. Densidade aparente: 0,95 a 1,02 g/cm³.",
        "handling_storage": "Baixa higroscopicidade (PCUR de 79% a 30 °C) e excelente fluidez física. Altamente compatível em misturas a granel com KCl, MAP e TSP.",
        "typical_nutrients": {"N (Nitrogênio)": 21.0, "S (Enxofre em Forma de Sulfato)": 24.0},
        "synonyms": ["Ammonium Sulphate", "SAM", "Sulfato Amônico"],
        "hs_ncm_codes": ["310221", "31022100"],
    },
    {
        "id": 8,
        "slug": "ssp",
        "canonical_name": "Superfosfato Simples (SSP)",
        "category_name": "Fertilizantes Fosfatados",
        "chemical_formula": "Ca(H2PO4)2 + CaSO4·2H2O",
        "cas_rn": "8011-76-5",
        "description": "Fertilizante fosfatado completo fornecendo Fósforo solúvel (18-20% P2O5), Enxofre (10-12% S) e Cálcio (18% Ca).",
        "detailed_description": "Produzido pelo ataque químico de rocha fosfática moída com ácido sulfúrico (H2SO4), gerando uma mistura íntima de fosfato monocálcico solúvel e sulfato de cálcio di-hidratado (gesso). Granulado com vapor e secado sob controle térmico.",
        "agronomic_usage": "Um dos fertilizantes mais consagrados da agricultura brasileira em solos de Cerrado com deficiência combinada de fósforo e enxofre. Utilizado na semeadura de soja, feijão, milho e formação de pastagens. O cálcio presente melhora o ambiente radicular em profundidade.",
        "physical_properties": "Grânulos cinzas ou marrons esferoidais, solubilidade parcial em água (cerca de 85% do fósforo é solúvel em água e citrato). pH levemente ácido (2,5 a 3,5). Densidade aparente: 0,95 a 1,05 g/cm³.",
        "handling_storage": "Moderadamente higroscópico (PCUR de 90% a 30 °C). Evitar exposição contínua à chuva e umidade para prevenir geração de acidez livre e amolecimento dos grânulos.",
        "typical_nutrients": {
            "P2O5 (Pentóxido de Fósforo Solúvel)": 20.0,
            "S (Enxofre em Forma de Sulfato)": 10.0,
            "Ca (Cálcio)": 18.0,
        },
        "synonyms": ["Single Superphosphate", "SSP", "Super Simples", "Superfosfato Normal"],
        "hs_ncm_codes": ["310319", "31031900"],
    },
    {
        "id": 9,
        "slug": "tsp",
        "canonical_name": "Superfosfato Triplo (TSP)",
        "category_name": "Fertilizantes Fosfatados",
        "chemical_formula": "Ca(H2PO4)2·H2O",
        "cas_rn": "65996-95-4",
        "description": "Fertilizante fosfatado altamente concentrado contendo 46% de P2O5 e 12% de Cálcio.",
        "detailed_description": "Fabricado pela digestão química de rocha fosfática concentrada com ácido fosfórico (H3PO4) de via úmida, eliminando a formação do gesso residual e concentrando o fosfato monocálcico purificado.",
        "agronomic_usage": "Ideal para formulações de misturas de plantio de alta graduação nutricional onde o aporte de fósforo concentrado é prioritário sem adição simultânea de nitrogênio. Muito empregado na adubação de base de leguminosas fixadoras de nitrogênio biológico (soja).",
        "physical_properties": "Grânulos cinzas rígidos e uniformes. Solubilidade superior a 85% em água e mais de 95% em citrato neutro de amônio. pH em solução de 2,5 a 3,0. Densidade: 0,95 a 1,02 g/cm³.",
        "handling_storage": "Estável em armazenagem sob condições normais de armazém ventilado (PCUR de 94% a 30 °C). Não deve ser misturado com ureia sem proteção em misturas físicas com tempo de repouso prolongado.",
        "typical_nutrients": {
            "P2O5 (Pentóxido de Fósforo Solúvel)": 46.0,
            "Ca (Cálcio)": 12.0,
        },
        "synonyms": ["Triple Superphosphate", "TSP", "Super Triplo", "Fosfato Concentrado"],
        "hs_ncm_codes": ["310311", "31031100"],
    },
    {
        "id": 10,
        "slug": "rocha-fosfatica",
        "canonical_name": "Rocha Fosfática Concentrada",
        "category_name": "Fertilizantes Fosfatados",
        "chemical_formula": "Ca10(PO4)6(F,OH,Cl)2",
        "cas_rn": "1306-05-4",
        "description": "Matéria-prima mineral de origem sedimentar ou ígnea contendo 28% a 32% de P2O5 total.",
        "detailed_description": "Mineral fosfático natural concentrado por britagem, moagem fina, separação magnética e flotação seletiva para enriquecer a concentração de apatitas e francolita e reduzir o teor de contaminantes e carbonatos.",
        "agronomic_usage": "Utilizada primariamente na indústria química para síntese de ácido fosfórico, MAP, DAP e superfosfatos. Na agricultura, também é empregada como fosfatagem corretiva de base em solos virgens ou na agricultura orgânica e sistemas regenerativos por sua liberação gradual de fósforo ao longo dos anos.",
        "physical_properties": "Pó fino ou concentrado arenoso fino de coloração castanha, cinza ou bege. Insolúvel em água, solúvel lentamente em ácidos orgânicos fracos do solo. Densidade aparente: 1,30 a 1,60 g/cm³.",
        "handling_storage": "Inerte, não higroscópica e quimicamente muito estável. Pode ser armazenada a granel em pátios cobertos ou silos sem risco de empedramento ou perda de teores.",
        "typical_nutrients": {
            "P2O5 (Pentóxido de Fósforo Total)": 30.0,
            "Ca (Cálcio)": 32.0,
        },
        "synonyms": ["Phosphate Rock", "Concentrado Fosfático", "Apatita Moída", "Fosforita"],
        "hs_ncm_codes": ["251010", "25101010", "251020"],
    },
    {
        "id": 11,
        "slug": "sulfato-de-potassio",
        "canonical_name": "Sulfato de Potássio (SOP)",
        "category_name": "Fertilizantes Potássicos",
        "chemical_formula": "K2SO4",
        "cas_rn": "7778-80-5",
        "description": "Fonte potássica nobre livre de cloro, contendo 50% de K2O e 18% de Enxofre.",
        "detailed_description": "Produzido pelo processo Mannheim (reação térmica de cloreto de potássio com ácido sulfúrico concentrado liberando ácido clorídrico gasoso) ou pela extração direta de sais minerais complexos como kainita e polihalita.",
        "agronomic_usage": "Fonte potássica indispensável para culturas de alto valor agregado sensíveis ao cloro (tabaco, batata, uva, citros, hortaliças e flores), e em solos salinizados ou fertirrigação em estufas protegidas. Apresenta índice salino muito inferior ao KCl (46 vs 116).",
        "physical_properties": "Grânulos ou pó cristalino branco puro. Solubilidade aquosa moderada (120 g/L a 20 °C). Solução neutra (pH 6,5 a 7,5). Densidade aparente: 1,10 a 1,20 g/cm³.",
        "handling_storage": "Baixíssima higroscopicidade (PCUR de 96% a 30 °C). Excelente conservação e estabilidade física durante armazenagem prolongada e mistura com outros adubos.",
        "typical_nutrients": {
            "K2O (Óxido de Potássio Solúvel)": 50.0,
            "S (Enxofre em Forma de Sulfato)": 18.0,
        },
        "synonyms": ["Sulphate of Potash", "SOP", "Potassium Sulphate", "Sulfato Potássico"],
        "hs_ncm_codes": ["310430", "31043000"],
    },
    {
        "id": 12,
        "slug": "enxofre-elementar",
        "canonical_name": "Enxofre Elementar Pastilhado",
        "category_name": "Macronutrientes Secundários",
        "chemical_formula": "S8",
        "cas_rn": "7704-34-9",
        "description": "Fonte pura e ultraconcentrada de Enxofre (99,5% S) para nutrição de plantas e condicionamento de solos.",
        "detailed_description": "Recuperado industrialmente pelo processo Claus a partir da dessulfurização de gás natural e correntes de refinarias petroquímicas, moldado na forma de pastilhas sólidas (pellets) ou formulado com 10% de bentonita dispersante para acelerar a quebra física no solo.",
        "agronomic_usage": "Fonte de enxofre de liberação gradual no solo. Para ser absorvido pelas raízes, necessita ser oxidado biologicamente por bactérias autótrofas do gênero Thiobacillus para a forma de sulfato (SO4²-). Excelente para suprimento contínuo em culturas de ciclo longo e correção de solos alcalinos.",
        "physical_properties": "Pastilhas ou esferas de cor amarela viva característica. Praticamente insolúvel em água líquida pura. Ponto de fusão em torno de 115 °C. Densidade aparente: 1,05 a 1,15 g/cm³.",
        "handling_storage": "Material sólido inflamável em pó suspenso, mas estável na forma pastilhada. Exige controle de faíscas estáticas em silos e correias transportadoras. Não higroscópico.",
        "typical_nutrients": {"S (Enxofre Elementar Puro)": 99.5},
        "synonyms": ["Elemental Sulfur", "Enxofre Pastilhado", "Brimstone", "Enxofre 99%"],
        "hs_ncm_codes": ["250300", "25030090"],
    },
]
